name = "vigesimo-sexto"
main = "index.js"
compatibility_date = "2026-10-03"

[vars]
GEMINI_MODEL = "gemini-3.5-flash-lite"
LIDIRE_PUBLIC_URL = "https://vigesimo-sexto.lidire-lifedirector.workers.dev"
RESEND_FROM_EMAIL = "LiDire <recuperacao@lidire.com>"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "lidire-mvp-db"
database_id = "1a095fd7-b0a0-4b83-b610-1b3a43fbb716"
